### PR TITLE
feat: normalize bool config parameters

### LINKED ISSUE #427: Normalize naming of boolean configuration parameters
## 📚 Context

Configuration parameters of type `bool` are not normalized (see [config.md for 2.0](https://github.com/cartesi/rollups-node/blob/next/2.0/docs/config.md))

## ✔️ Solution

As a suggestion by @endersonmaia captured at https://github.com/cartesi/rollups-node/issues/426#issuecomment-2127655208, we could use suffixes `ENABLED`/`DISABLED` for all `bool` arguments to imply state and normalize their meaning.

## 📈 Subtasks

- [x] Evaluate possible solutions along with the one listed above
- [x] Apply changes and update docs
- [x] Execute unit tests

### PR DESCRIPTION
**Pull request by marcelstanley**
Applied suffixes ENABLED/DISABLED to boolean parameters to match the node internal state.

Closes #427

### CODE REVIEW

**Comment by endersonmaia** [comment]
I thought `true` could be the default value for all those flags.

In a sense, if `CARTESI_LOG_PRETTY` being disabled is the default, then the variable should be named like `CARTESI_LOG_PRETTY_DISABLED=true`.

This way, if one needs to enable it, it will be necessary to explicitly set this to false, like `CARTESI_LOG_PRETTY_DISABLED=false`.

Also, if `CARTESI_FEATURE_MACHINE_HASH_CHECK` enabled is the default, then the variable should be `CARTESI_FEATURE_MACHINE_HASH_CHECK_ENABLE=true`, and if one needs to disable it, it will be required to explicitly set it to false like `CARTESI_FEATURE_MACHINE_HASH_CHECK_ENABLE=true`.

Does that make sense?

If yes, we'd have:

- `CARTESI_LEGACY_BLOCKCHAIN_DISABLED=true`
- `CARTESI_FEATURE_CLAIMER_DISABLED=true`
- `CARTESI_FEATURE_MACHINE_HASH_CHECK_ENABLED=tue`
- `CARTESI_EXPERIMENTAL_SERVER_MANAGER_LOG_BYPASS_DISABLED=true`
- `CARTESI_LOG_PRETTY_DISABLED=true`

**Review by torives — COMMENTED** [review]
This can be quite contentious because you know, naming things is hard and mostly opinion-based. But my five cents is that we should avoid at all costs the cognitive load of dealing with double negatives.

`!LogPrettyDisabled` is harder to reason about than `!LogPrettyEnabled` as you have to consider the negation sign AND the variable name.

I propose to name them all with `_ENABLED` and set the default accordingly. We don't get the shared convention were all boolean vars are true or false by default, but we also don't have to deal with double negatives in the code (which is more important, IMO).

**Comment by endersonmaia** [comment]
Yeah, I agree with you now that you make the point about the code.

I'm biased about configuring and running the node, and less about
maintaining the code itself.

Em ter., 11 de jun. de 2024, 20:47, Victor Yves ***@***.***>
escreveu:

**Comment by torives** [comment]
> I'm biased about configuring and running the node, and less about maintaining the code itself.

@endersonmaia Which is perfectly natural. That is why your opinion is important, we get a different perspective and try to meet halfway 😉

**Review by torives — APPROVED** [review]

**Review by endersonmaia — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
