### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by omahs**
fix: typos

### CODE REVIEW

**Comment by gligneul** [comment]
@omahs, thanks for the submission. Could you please squash all these commits and change the message to use conventional commits? More details in our [contributing file](https://github.com/cartesi/rollups-node/blob/main/CONTRIBUTING.md).

**Review by marcelstanley — CHANGES_REQUESTED** [review]

**Comment by marcelstanley** [comment]
Thanks for the contribution, @omahs! Please check my comments as well.

**Comment by omahs** [comment]
Hey @gligneul and @marcelstanley, I just added the changes!

**Comment by gligneul** [comment]
The CI is failing because the PR is from a fork, we will merge it into main in https://github.com/cartesi/rollups-node/pull/118

**Pull request merged**
