### PR TITLE
feat: replace log with slog

### LINKED ISSUE #235: Use slog
## 📚 Context

This issue aims to refactor the Go code to use the [`log/slog`](https://pkg.go.dev/log/slog) package instead of a custom-made one. Then, we can use the [`tint`](https://github.com/lmittmann/tint) package to make the log pretty in the local environment. By default, the log handler should be JSON or something that is easy to parse automatically in a cloud environment.

### PR DESCRIPTION
**Pull request by torives**
- Adds structured logging with slog
- Rust service's messages are now logged in the correct level
- Adds CARTESI_LOG_PRETTY
- Removes CARTESI_LOG_TIMESTAMP
- cartesi-rollups-cli now prints to stdout directly instead of using a logger

Closes #235

### CODE REVIEW

**Comment by torives** [comment]
@endersonmaia this PR became quite large, so I'll tackle the log-related issues of #308 in a future one 😉

**Review by gligneul — APPROVED** [review]
I did a quick look, and it looks good! @renan061 should take a look as well.

**Comment by torives** [comment]
@gligneul so that you know what changed, I fixed [this line](https://github.com/cartesi/rollups-node/pull/319/files#diff-477c41528e85ed9dcbf01ce5c37cb42469e502ae9afa6aeb9c49a588d4e58af4R100). I assigned twice to `slog.LevelError` 😅

**Comment by endersonmaia** [comment]
Loving the `service=` key :heart:

**Comment by torives** [comment]
This will be rebased on top of #318 after it is merged to improve how the node's configuration is logged.

**Comment by renan061** [comment]
> I did a quick look, and it looks good! @renan061 should take a look as well.

I just saw this.

@torives , should I review or wait for the rebase?

**Comment by torives** [comment]
> > I did a quick look, and it looks good! @renan061 should take a look as well.
> 
> I just saw this.
> 
> @torives , should I review or wait for the rebase?

You should wait for the rebase. I'll revert this to a draft to avoid confusion.

**Comment by torives** [comment]
Due to the change in scope in #318, it has become the new base for this PR.

**Pull request closed without merging**
