### PR TITLE
Bum Rust to 1.78.0

### LINKED ISSUE #400: Bump Rust version to 1.78.0
## 📈 Subtasks

- [ ] Rust
    - [ ] Bump Rust version in Docker image.
    - [ ] Bump Rust version in AuthorityClaimer.
- [ ] Verify whether everything is working as expected.

### PR DESCRIPTION
**Pull request by fmoura**
Closes #400

### CODE REVIEW

**Review by marcelstanley — COMMENTED** [review]
I'm wondering if you could:
1. Split the bump itself and the clippy changes into two separate commits
2. Provide more details in the "clippy" commit regarding what issues were circumvented/bypassed the changes

**Comment by fmoura** [comment]
Is it valid to have a "broken" Commit ? because just bumping the Rust version will leave it broken. And I can add the details at the single commit

**Comment by marcelstanley** [comment]
> Is it valid to have a "broken" Commit ? because just bumping the Rust version will leave it broken. And I can add the details at the single commit

As long as the commit with the fix is merged alongside the broken commit, I don't se a problem. But I'm fine with a single commit as well, if you prefer.

**Comment by fmoura** [comment]
Dead Code removed

**Review by gligneul — APPROVED** [review]

**Review by marcelstanley — APPROVED** [review]

**Pull request merged**
